-- ZAD 1A

CREATE TABLE A6_LRS (GEOM SDO_GEOMETRY);

-- ZAD 1B

INSERT INTO A6_LRS
SELECT SR.GEOM
FROM   STREETS_AND_RAILROADS SR, MAJOR_CITIES MC
WHERE SDO_WITHIN_DISTANCE(SR.GEOM, SDO_GEOMETRY(2001,8307,
    MC.GEOM.SDO_POINT, MC.GEOM.SDO_ELEM_INFO, MC.GEOM.SDO_ORDINATES),'distance=10 unit=km') = 'TRUE' AND MC.CITY_NAME = 'Koszalin';

-- ZAD 1C

SELECT SDO_GEOM.SDO_LENGTH(GEOM)/1000 DISTANCE, SDO_UTIL.GETNUMVERTICES(GEOM) ST_NUMPOINTS from A6_LRS;

-- ZAD 1D

UPDATE A6_LRS
SET GEOM = (SELECT SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0, 276.681) FROM A6_LRS);

-- ZAD 1E

INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('A6_LRS','GEOM',
MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
    MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
    MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1) ),
    8307);
    
-- ZAD 1F

CREATE INDEX LRS_A6_IDX ON A6_LRS(GEOM)INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- ZAD 2A

SELECT SDO_LRS.VALID_MEASURE(GEOM, 500) AS VALID_500
FROM A6_LRS

-- ZAD 2B

SELECT SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) AS END_PT
FROM A6_LRS

-- ZAD 2C

SELECT SDO_LRS.LOCATE_PT(GEOM, 150, 0) AS KM150
FROM A6_LRS;

-- ZAD 2D

SELECT SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) AS CLIPPED
FROM A6_LRS;

-- ZAD 2E

SELECT SDO_LRS.GET_NEXT_SHAPE_PT (A.GEOM, MC.GEOM) AS WJAZD_NA_A6
FROM A6_LRS A, MAJOR_CITIES MC
WHERE MC.CITY_NAME = 'Slupsk';

-- ZAD 2F

SELECT SDO_GEOM.SDO_LENGTH(SDO_LRS.OFFSET_GEOM_SEGMENT(A.GEOM, M.DIMINFO, 50, 200, 50, 'unit=m'),1,'unit=km') AS KOSZT
FROM A6_LRS A, USER_SDO_GEOM_METADATA M
WHERE M.TABLE_NAME = 'A6_LRS' AND M.COLUMN_NAME = 'GEOM';