--ZAD 1

CREATE TABLE MOVIES (
    ID NUMBER(12) PRIMARY KEY,
    TITLE VARCHAR2(400) NOT NULL,
    CATEGORY VARCHAR(50),
    YEAR CHAR(4),
    CAST VARCHAR2(4000),
    DIRECTOR VARCHAR2(4000),
    STORY VARCHAR2(4000),
    PRICE NUMBER(5,2),
    COVER BLOB,
    MIME_TYPE VARCHAR2(50)
);

--ZAD 2

INSERT INTO MOVIES
(ID, TITLE, CATEGORY, YEAR, CAST, DIRECTOR, STORY, PRICE, COVER, MIME_TYPE)
SELECT D.ID, D.TITLE, D.CATEGORY, SUBSTR(D.YEAR,1,4), D.CAST, D.DIRECTOR, D.STORY, D.PRICE, C.IMAGE, C.MIME_TYPE
FROM DESCRIPTIONS D LEFT OUTER JOIN COVERS C ON D.ID=C.MOVIE_ID;

--ZAD 3

SELECT ID, TITLE FROM MOVIES WHERE COVER IS NULL;

-- ZAD 4

SELECT ID, TITLE, dbms_lob.getlength(COVER) AS FILESIZE FROM MOVIES WHERE COVER IS NOT NULL;

-- ZAD 5

SELECT ID, TITLE, dbms_lob.getlength(COVER) AS FILESIZE FROM MOVIES WHERE COVER IS NULL;

-- ZAD 6

SELECT * FROM ALL_DIRECTORIES;

-- ZAD 7

UPDATE MOVIES SET COVER = EMPTY_BLOB(), MIME_TYPE = 'image/jpg' WHERE ID = 66;
COMMIT;

-- ZAD 8

SELECT ID, TITLE, dbms_lob.getlength(COVER) AS FILESIZE FROM MOVIES WHERE ID IN (65,66);

-- ZAD 9

DECLARE
    LOB_OBJ BLOB;
    LOC BFILE := BFILENAME('ZSBD_DIR', 'escape.jpg');
BEGIN
    DBMS_LOB.FILEOPEN(LOC, DBMS_LOB.file_readonly);
    SELECT COVER INTO LOB_OBJ FROM MOVIES WHERE ID = 66 FOR UPDATE;
    DBMS_LOB.LOADFROMFILE(LOB_OBJ, LOC, DBMS_LOB.getlength(LOC));
    DBMS_LOB.FILECLOSE(LOC);
    COMMIT;
END;

-- ZAD 10

CREATE TABLE TEMP_COVERS(
    MOVIE_ID NUMBER(12),
    IMAGE BFILE,
    MIME_TYPE VARCHAR2(50)
);

-- ZAD 11

INSERT INTO TEMP_COVERS VALUES (65, BFILENAME('ZSBD_DIR', 'eagles.jpg'), 'image/jpg');

-- ZAD 12

SELECT MOVIE_ID, dbms_lob.getlength(IMAGE) AS FILESIZE FROM TEMP_COVERS;

-- ZAD 13

DECLARE
    LOB_OBJ BLOB;
    LOC BFILE;
    MIME_T VARCHAR2(50);
BEGIN
    SELECT IMAGE, MIME_TYPE INTO LOC, MIME_T FROM TEMP_COVERS WHERE MOVIE_ID = 65;
    
    DBMS_LOB.CREATETEMPORARY(LOB_OBJ, TRUE);
    DBMS_LOB.FILEOPEN(LOC, DBMS_LOB.file_readonly);
    DBMS_LOB.LOADFROMFILE(LOB_OBJ, LOC, DBMS_LOB.getlength(LOC));
    DBMS_LOB.FILECLOSE(LOC);
    
    UPDATE MOVIES SET COVER = LOB_OBJ, MIME_TYPE = MIME_T WHERE ID = 65;
    
    dbms_lob.freetemporary(LOB_OBJ);
    COMMIT;
END;

-- ZAD 14

SELECT ID AS MOVIE_ID, dbms_lob.getlength(COVER) AS FILESIZE FROM MOVIES WHERE ID IN (65,66);

-- ZAD 15

DROP TABLE MOVIES;
DROP TABLE TEMP_COVERS;